name: Python Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install flake8 pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run flake8
      run: flake8 --ignore=E501 src/ tests/
    - name: Run pylint in src/
      run: pylint src/
    - name: Run pylint in tests/
      run: pylint tests/
    - name: Run unit tests
      run: |
        python -m unittest discover -s tests